### ISSUE TITLE
Problems with Testuser

### ISSUE THREAD

**Issue by ghellstern** [HAWK-Digital-Environments/HAWKI#73]
I wanted to to try HAWKI in a simple local setup with a testuser. 

In .env I therefore specified:

```
Authentication="LDAP"
# LDAP config
#LDAP_HOST="ldaps://..."
#LDAP_BASE_DN="cn=...,ou=...,dc=..."
#LDAP_BIND_PW="..."
#LDAP_SEARCH_DN="ou=...,dc=..."
#LDAP_PORT=""
#; Choose the filter based on your LDAP configuration. the value "username" is used as a placeholder and will be replaced with the actual #username in authentication function.
#; EXAMPLES:
#; (|(sAMAccountName=username)(mail=username))
#; (|(uid=username)(mail=username))
#LDAP_FILTER="(|(sAMAccountName=username)(mail=username))"

# Testuser accout
TESTUSER="test"
TESTPASSWORD="test"


```
When submitting the login and the password the following error appears on the web-server:

 [::1]:58325 [500]: POST /login - Uncaught Error: Call to undefined function ldap_escape() in C:\....\HAWKI\private\app\php\auth.php:138
Stack trace:
#0 C:\...\HAWKI\private\pages\login.php(17): require_once()
#1 C:\....\HAWKI\index.php(18): include_once('...')
#2 {main}
  thrown in C:\...\HAWKI\private\app\php\auth.php on line 138

Any idea whats going wrong?? 

Thanks a lot for a hint!!

**Comment by ItsNotYou** [comment]
Did you install the dependencies via composer? See https://getcomposer.org/doc/01-basic-usage.md and https://github.com/HAWK-Digital-Environments/HAWKI/blob/main/composer_install.sh for details.

```
php composer.phar update
```

**Comment by Ariansdf** [comment]
Hey @ghellstern,
did you try @ItsNotYou's suggestion?
I've never had this issue myself. Ldap escape is already in php 8. you can check [here](https://www.php.net/manual/en/function.ldap-escape.php) for more info.
but the code itself is meant to prevent code injection. I think if you comment out the line, you can still test the rest of the project.

**Comment by ghellstern** [comment]
Hi @Adriansdf! 
The hint by @ItsNotYou unfortunately did't help - but commenting out the line with Ldap escape did :-) Since I want to test only locally, it will not harm... 
Thanks a lot for your support !

**Comment by ghellstern** [comment]
Workaround helped.

**Comment by ShUl0w** [comment]
Hi @ghellstern,

I ran into the same issue when dockerizing HAWKI for local development. In my case, my PHP-image (8-bullseye) was missing `libldap2-dev` and the LDAP extension. Depending on your setup, you might want to try and install those to fix the issue.

**Comment by DanielBarie** [comment]
@ShUl0w: Would you mind sharing your Docker instructions?

**Comment by ShUl0w** [comment]
Hi @DanielBarie,

sure, I set up a [basic repository](https://github.com/ShUl0w/HAWKI-Dockerfiles) with a working php-apache based Dockerfile for HAWKI. Please note that this is not equivalent to what I'm using for local development, which is a bit more involved.

@Ariansdf I don't know if its any help for the project, but maybe it would be a good idea to provide a docker image / documentation for trying HAWKI locally for the less tech-savy?

**Comment by DanielBarie** [comment]
@ShUl0w: Appreciate! Makes life a little bit easier. 

@Ariansdf: Would you mind extending the readme for more detailed setup instructions? Or maybe have a Wiki?

**Comment by Ariansdf** [comment]
@ShUl0w
I'm sure Docker will facilitate the deployment process and we will definitely include it in our next main release. 
Unfortunately at the moment I don't have the capacity but our colleagues at Hochschule Munich and Cologne University are working on it.

**Comment by Ariansdf** [comment]
> @ShUl0w: Appreciate! Makes life a little bit easier.
> 
> @Ariansdf: Would you mind extending the readme for more detailed setup instructions? Or maybe have a Wiki?

I'm working on a detailed documentation for the next main release.

**Comment by ShUl0w** [comment]
@Ariansdf Awesome; in case I can be of help, feel free to reach out. I will keep my repo up until there's an official image / documentation, and dispose of it once those are implemented.

**Comment by Ariansdf** [comment]
> @Ariansdf Awesome; in case I can be of help, feel free to reach out. I will keep my repo up until there's an official image / documentation, and dispose of it once those are implemented.

That sounds fantastic!
We are in the process of starting collaborations with some colleagues, and we would love for you to join our weekly meetings. If you're interested, please email me ( arian.sadafi1@hawk.de ), and I'll be happy to send you an invitation.
